### ISSUE TITLE
Make this a Python library on PyPI

### ISSUE THREAD

**Issue by rrooggiieerr** [valletw/pyummeter#1]
Hi!

I see you're also a Home Assistant user. I like to make an HA integration for my UM Meter so I can track power usage of some USB devices. I stumbled on your code while doing some research. Would you be interested in making this into a library on PyPI so I can use it in my integration? If you're interested we can work on this together, I can give you directions on how to do this.

Also under what software licence is your code released?

Keep up the good work!

**Comment by rrooggiieerr** [comment]
I read in your pyproject.toml that it's licensed under the MIT license, so that answers one question

**Comment by valletw** [comment]
Hi!
Interesting feature, I didn't think about using it on HA.
I will have a look to generate the library. I may found some time to do it in the next days/weeks.

You only need the `UMeter` class ? No need of CSV (it was for my test / project)

**Comment by rrooggiieerr** [comment]
Hi, good to hear back from you.

I have actually already forked your project and refactored the file structure to fit a new library. Also managed to build it using `python3 -m build`. Of course I didn't put it on PyPI I leave that up to you.

Have a look on my github and let me know what you think. I will also create a pull request so you can incorporate my changes if you think they are useful

**Comment by valletw** [comment]
Hi,

I pushed the library with tag `0.1.0`. You can try to use it on your project.
I didn't make the modification for the `is_open` because I had to modify the mock process for the test (not enough time for this).

**Comment by rrooggiieerr** [comment]
Thanks @valletw , i'm going to have a look at it!
